[build]
builder = "nixpacks"
dockerfilePath = "./backend/Dockerfile"

[deploy]
numReplicas = 1
startCommand = "cd backend && node app.js"
healthcheckPath = "/api/anime/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 