[build]
builder = "nixpacks"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
PORT = "3000" 