[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && node app.js"
healthcheckPath = "/api/anime/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 